spring:
  servlet:
    multipart:
      max-file-size: 10MB # 파일 업로드 제한
      max-request-size: 10MB
  cloud:
    aws:
      s3:
        bucket: springbootmini
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      stack:
        auto: false
server:
  port: 8081